In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_excel("gdp per capita.xls")
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
0,Last Updated Date,2023-06-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000
3,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,5.635318,-0.709567,2.885166,1.515938,4.917139,4.738330,0.181216,-18.698324,17.225300,NaN
4,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-2.342974,5.093992,2.330796,1.724021,2.436215,...,1.400457,1.186759,0.166840,-0.490259,-0.105886,-0.169822,-0.587557,-5.421662,1.683557,0.842507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.702936,3.653588,7.371867,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527,4.924753
265,"Yemen, Rep.",YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.868808,-2.955389,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,NaN,NaN
266,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.977924,3.061899,4.165498,4.685237,2.892205,...,1.099462,-0.172221,-0.757928,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315,1.187663
267,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-1.787685,-5.541489,0.023361,8.686086,12.972033,...,1.676101,1.352928,-0.312861,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097,1.895518
268,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,3.076210,-1.666989,2.985427,-4.143906,1.682986,...,0.988283,-0.715190,-0.132760,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613,1.328184

In [3]:
index_list = list(range(0,2))
df.drop(df.index[index_list], inplace =True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000
3,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,5.635318,-0.709567,2.885166,1.515938,4.917139,4.738330,0.181216,-18.698324,17.225300,NaN
4,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-2.342974,5.093992,2.330796,1.724021,2.436215,...,1.400457,1.186759,0.166840,-0.490259,-0.105886,-0.169822,-0.587557,-5.421662,1.683557,0.842507
5,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.002522,-0.964803,-1.666416,-0.345802,-0.253594,-1.688577,0.932833,-5.364666,-22.929194,NaN
6,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-0.255511,1.592942,4.978710,3.130231,1.798761,...,3.257923,3.093635,0.026016,-2.519274,-0.382691,0.140162,0.563580,-3.453124,1.372160,1.192668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.702936,3.653588,7.371867,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527,4.924753
265,"Yemen, Rep.",YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.868808,-2.955389,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,NaN,NaN
266,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.977924,3.061899,4.165498,4.685237,2.892205,...,1.099462,-0.172221,-0.757928,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315,1.187663
267,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-1.787685,-5.541489,0.023361,8.686086,12.972033,...,1.676101,1.352928,-0.312861,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097,1.895518
268,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,3.076210,-1.666989,2.985427,-4.143906,1.682986,...,0.988283,-0.715190,-0.132760,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613,1.328184

In [4]:
index_list = list(range(1,14))
df.drop(df.index[index_list], inplace =True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000
16,Australia,AUS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.463671,-1.147700,4.198486,4.901197,3.923740,...,0.828326,1.060337,0.693066,1.138424,0.604963,1.348283,0.665151,-1.278358,2.105711,2.457503
17,Austria,AUT,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,4.960717,2.021470,3.471466,5.419336,2.810013,...,-0.562299,-0.122371,-0.111540,0.892469,1.550724,1.927713,1.066970,-6.841545,4.102317,3.989869
18,Azerbaijan,AZE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.450020,1.475937,-0.103121,-4.177172,-0.778416,0.624486,1.635850,-4.952702,5.151500,4.233365
19,Burundi,BDI,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-15.870158,6.365246,1.990096,3.291864,1.135991,...,1.263599,0.810603,-5.980496,-2.206134,-1.772646,-1.377140,-1.457193,-2.508461,0.381167,-0.824628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.702936,3.653588,7.371867,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527,4.924753
265,"Yemen, Rep.",YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.868808,-2.955389,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,NaN,NaN
266,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.977924,3.061899,4.165498,4.685237,2.892205,...,1.099462,-0.172221,-0.757928,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315,1.187663
267,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-1.787685,-5.541489,0.023361,8.686086,12.972033,...,1.676101,1.352928,-0.312861,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097,1.895518
268,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,3.076210,-1.666989,2.985427,-4.143906,1.682986,...,0.988283,-0.715190,-0.132760,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613,1.328184

In [5]:
index_list = list(range(2,69))
df.drop(df.index[index_list],inplace=True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000
16,Australia,AUS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.463671,-1.147700,4.198486,4.901197,3.923740,...,0.828326,1.060337,0.693066,1.138424,0.604963,1.348283,0.665151,-1.278358,2.105711,2.457503
84,United Kingdom,GBR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,1.899262,0.248519,4.092469,4.849645,1.488048,...,1.140213,2.442466,1.584979,1.393849,1.749954,1.090624,1.032741,-11.355676,7.685657,4.186942
85,Georgia,GEO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.933646,4.382901,2.860094,2.844902,4.828570,4.883855,5.162619,-6.824433,10.885702,9.993288
86,Ghana,GHA,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.555959,1.647509,1.927484,-0.224811,-1.059513,...,4.712772,0.409401,-0.265333,0.983232,5.739078,3.969547,4.305978,-1.541637,3.262282,1.257188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.702936,3.653588,7.371867,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527,4.924753
265,"Yemen, Rep.",YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.868808,-2.955389,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,NaN,NaN
266,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.977924,3.061899,4.165498,4.685237,2.892205,...,1.099462,-0.172221,-0.757928,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315,1.187663
267,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-1.787685,-5.541489,0.023361,8.686086,12.972033,...,1.676101,1.352928,-0.312861,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097,1.895518
268,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,3.076210,-1.666989,2.985427,-4.143906,1.682986,...,0.988283,-0.715190,-0.132760,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613,1.328184

In [6]:
index_list = list(range(3,99))
df.drop(df.index[index_list], inplace =True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000
16,Australia,AUS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.463671,-1.147700,4.198486,4.901197,3.923740,...,0.828326,1.060337,0.693066,1.138424,0.604963,1.348283,0.665151,-1.278358,2.105711,2.457503
84,United Kingdom,GBR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,1.899262,0.248519,4.092469,4.849645,1.488048,...,1.140213,2.442466,1.584979,1.393849,1.749954,1.090624,1.032741,-11.355676,7.685657,4.186942
181,Nepal,NPL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-0.030599,-0.071562,-0.108267,5.381354,-3.227262,...,3.332856,5.700533,3.417884,-0.471182,7.731269,6.401863,5.451917,-4.086569,2.442380,3.840995
182,Nauru,NRU,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.101433,12.626580,-7.726824,5.620355,-8.442793,5.730518,6.400845,2.688330,1.634464,1.093586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.702936,3.653588,7.371867,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527,4.924753
265,"Yemen, Rep.",YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.868808,-2.955389,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,NaN,NaN
266,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.977924,3.061899,4.165498,4.685237,2.892205,...,1.099462,-0.172221,-0.757928,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315,1.187663
267,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-1.787685,-5.541489,0.023361,8.686086,12.972033,...,1.676101,1.352928,-0.312861,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097,1.895518
268,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,3.076210,-1.666989,2.985427,-4.143906,1.682986,...,0.988283,-0.715190,-0.132760,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613,1.328184

In [7]:
index_list = list(range(4,12))
df.drop(df.index[index_list], inplace =True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000
16,Australia,AUS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.463671,-1.147700,4.198486,4.901197,3.923740,...,0.828326,1.060337,0.693066,1.138424,0.604963,1.348283,0.665151,-1.278358,2.105711,2.457503
84,United Kingdom,GBR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,1.899262,0.248519,4.092469,4.849645,1.488048,...,1.140213,2.442466,1.584979,1.393849,1.749954,1.090624,1.032741,-11.355676,7.685657,4.186942
181,Nepal,NPL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-0.030599,-0.071562,-0.108267,5.381354,-3.227262,...,3.332856,5.700533,3.417884,-0.471182,7.731269,6.401863,5.451917,-4.086569,2.442380,3.840995
190,Philippines,PHL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,2.613696,1.916292,4.059426,0.574464,2.490604,...,4.964801,4.642336,4.587218,5.265571,5.064393,4.548701,4.376526,-10.978194,4.146514,6.007700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.702936,3.653588,7.371867,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527,4.924753
265,"Yemen, Rep.",YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.868808,-2.955389,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,NaN,NaN
266,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.977924,3.061899,4.165498,4.685237,2.892205,...,1.099462,-0.172221,-0.757928,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315,1.187663
267,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-1.787685,-5.541489,0.023361,8.686086,12.972033,...,1.676101,1.352928,-0.312861,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097,1.895518
268,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,3.076210,-1.666989,2.985427,-4.143906,1.682986,...,0.988283,-0.715190,-0.132760,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613,1.328184

In [8]:
index_list = list(range(5,83))
df.drop(df.index[index_list], inplace =True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000
16,Australia,AUS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.463671,-1.147700,4.198486,4.901197,3.923740,...,0.828326,1.060337,0.693066,1.138424,0.604963,1.348283,0.665151,-1.278358,2.105711,2.457503
84,United Kingdom,GBR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,1.899262,0.248519,4.092469,4.849645,1.488048,...,1.140213,2.442466,1.584979,1.393849,1.749954,1.090624,1.032741,-11.355676,7.685657,4.186942
181,Nepal,NPL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-0.030599,-0.071562,-0.108267,5.381354,-3.227262,...,3.332856,5.700533,3.417884,-0.471182,7.731269,6.401863,5.451917,-4.086569,2.442380,3.840995
190,Philippines,PHL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,2.613696,1.916292,4.059426,0.574464,2.490604,...,4.964801,4.642336,4.587218,5.265571,5.064393,4.548701,4.376526,-10.978194,4.146514,6.007700

In [9]:
header_row = 0
df.columns = df.iloc[header_row]
df

2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000
16,Australia,AUS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.463671,-1.147700,4.198486,4.901197,3.923740,...,0.828326,1.060337,0.693066,1.138424,0.604963,1.348283,0.665151,-1.278358,2.105711,2.457503
84,United Kingdom,GBR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,1.899262,0.248519,4.092469,4.849645,1.488048,...,1.140213,2.442466,1.584979,1.393849,1.749954,1.090624,1.032741,-11.355676,7.685657,4.186942
181,Nepal,NPL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-0.030599,-0.071562,-0.108267,5.381354,-3.227262,...,3.332856,5.700533,3.417884,-0.471182,7.731269,6.401863,5.451917,-4.086569,2.442380,3.840995
190,Philippines,PHL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,2.613696,1.916292,4.059426,0.574464,2.490604,...,4.964801,4.642336,4.587218,5.265571,5.064393,4.548701,4.376526,-10.978194,4.146514,6.007700

In [10]:
df.drop([2],inplace=True)
df

2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
16,Australia,AUS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.463671,-1.147700,4.198486,4.901197,3.923740,...,0.828326,1.060337,0.693066,1.138424,0.604963,1.348283,0.665151,-1.278358,2.105711,2.457503
84,United Kingdom,GBR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,1.899262,0.248519,4.092469,4.849645,1.488048,...,1.140213,2.442466,1.584979,1.393849,1.749954,1.090624,1.032741,-11.355676,7.685657,4.186942
181,Nepal,NPL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-0.030599,-0.071562,-0.108267,5.381354,-3.227262,...,3.332856,5.700533,3.417884,-0.471182,7.731269,6.401863,5.451917,-4.086569,2.442380,3.840995
190,Philippines,PHL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,2.613696,1.916292,4.059426,0.574464,2.490604,...,4.964801,4.642336,4.587218,5.265571,5.064393,4.548701,4.376526,-10.978194,4.146514,6.007700

In [11]:
df=df.reset_index()
df

2,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
0,16,Australia,AUS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.463671,-1.147700,4.198486,4.901197,...,0.828326,1.060337,0.693066,1.138424,0.604963,1.348283,0.665151,-1.278358,2.105711,2.457503
1,84,United Kingdom,GBR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,1.899262,0.248519,4.092469,4.849645,...,1.140213,2.442466,1.584979,1.393849,1.749954,1.090624,1.032741,-11.355676,7.685657,4.186942
2,181,Nepal,NPL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-0.030599,-0.071562,-0.108267,5.381354,...,3.332856,5.700533,3.417884,-0.471182,7.731269,6.401863,5.451917,-4.086569,2.442380,3.840995
3,190,Philippines,PHL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,2.613696,1.916292,4.059426,0.574464,...,4.964801,4.642336,4.587218,5.265571,5.064393,4.548701,4.376526,-10.978194,4.146514,6.007700

In [12]:
df.drop([1960.0],inplace=True, axis=1)
df

2,index,Country Name,Country Code,Indicator Name,Indicator Code,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
0,16,Australia,AUS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,0.463671,-1.147700,4.198486,4.901197,3.923740,...,0.828326,1.060337,0.693066,1.138424,0.604963,1.348283,0.665151,-1.278358,2.105711,2.457503
1,84,United Kingdom,GBR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,1.899262,0.248519,4.092469,4.849645,1.488048,...,1.140213,2.442466,1.584979,1.393849,1.749954,1.090624,1.032741,-11.355676,7.685657,4.186942
2,181,Nepal,NPL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,-0.030599,-0.071562,-0.108267,5.381354,-3.227262,...,3.332856,5.700533,3.417884,-0.471182,7.731269,6.401863,5.451917,-4.086569,2.442380,3.840995
3,190,Philippines,PHL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,2.613696,1.916292,4.059426,0.574464,2.490604,...,4.964801,4.642336,4.587218,5.265571,5.064393,4.548701,4.376526,-10.978194,4.146514,6.007700

In [13]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  
    display(df)

2,index,Country Name,Country Code,Indicator Name,Indicator Code,1961.0,1962.0,1963.0,1964.0,1965.0,1966.0,1967.0,1968.0,1969.0,1970.0,1971.0,1972.0,1973.0,1974.0,1975.0,1976.0,1977.0,1978.0,1979.0,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,1987.0,1988.0,1989.0,1990.0,1991.0,1992.0,1993.0,1994.0,1995.0,1996.0,1997.0,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
0,16,Australia,AUS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,0.463671,-1.147700,4.198486,4.901197,3.923740,0.068020,4.971516,3.256267,4.828380,5.085013,0.544150,2.017709,1.062445,1.504868,0.096321,1.565296,2.434209,-0.273326,2.931672,1.787268,1.738083,1.548904,-3.553486,3.343577,3.885135,2.473225,1.010994,4.041072,2.131740,2.054794,-1.644753,-0.689506,3.125986,2.984298,2.736499,2.603790,2.794518,3.575819,3.814385,2.718829,0.739613,2.817325,1.932213,3.108287,1.905683,1.363514,1.901151,1.513510,-0.207409,0.628837,0.978468,2.103808,0.828326,1.060337,0.693066,1.138424,0.604963,1.348283,0.665151,-1.278358,2.105711,2.457503
1,84,United Kingdom,GBR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,1.899262,0.248519,4.092469,4.849645,1.488048,1.014665,2.234412,4.929077,1.501173,6.255522,3.073314,3.968556,6.318245,-2.545877,-1.466335,2.935589,2.491438,4.198675,3.655966,-2.148387,-0.822285,2.031456,4.186321,2.107380,3.911319,2.911710,5.168872,5.497881,2.310929,0.433081,-1.408486,0.129933,2.244411,3.581968,2.260784,1.648562,4.255208,2.857118,2.671187,3.721393,1.764903,1.340843,2.643986,1.764340,1.965820,1.412230,1.767935,-0.937078,-5.230035,1.630274,0.280839,0.745479,1.140213,2.442466,1.584979,1.393849,1.749954,1.090624,1.032741,-11.355676,7.685657,4.186942
2,181,Nepal,NPL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,-0.030599,-0.071562,-0.108267,5.381354,-3.227262,4.826629,-3.633059,-1.467746,2.230459,0.365411,-3.311370,0.926624,-2.594050,4.067922,-0.723684,2.159571,0.753556,2.033172,0.019049,-4.585257,5.836237,1.383890,-5.258216,7.115664,3.730635,2.255047,-0.464560,5.427091,2.017283,2.120295,3.650932,1.233195,1.089816,5.597379,1.098920,3.116692,2.945563,1.043659,2.510433,4.399653,3.134542,-1.366341,2.525547,3.390143,2.372370,2.453080,2.657917,5.441961,3.970721,4.296893,3.024180,4.423907,3.332856,5.700533,3.417884,-0.471182,7.731269,6.401863,5.451917,-4.086569,2.442380,3.840995
3,190,Philippines,PHL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,2.613696,1.916292,4.059426,0.574464,2.490604,1.654767,2.450210,2.295504,2.014068,1.037780,2.684019,2.780126,6.106613,0.941190,2.948527,6.076264,2.791524,2.340337,2.766148,2.451575,0.799596,1.134998,-0.602998,-9.289393,-9.063524,1.117667,1.989138,4.262220,3.762013,0.685480,-2.775217,-1.921961,-0.199033,1.956092,2.207628,3.331903,2.620545,-2.882087,0.964851,2.094019,0.890743,1.598835,2.987190,4.472465,2.930610,3.350809,4.545525,2.410934,-0.401300,5.418030,2.024220,5.049330,4.964801,4.642336,4.587218,5.265571,5.064393,4.548701,4.376526,-10.978194,4.146514,6.007700