In [2]:
import pandas as pd
df=pd.read_excel("Net migration.xls")
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
0,Last Updated Date,2023-06-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
3,Aruba,ABW,Net migration,SM.POP.NETM,0.0,-569.0,-609.0,-646.0,-684.0,-726.0,...,134.0,88.0,177.0,170.0,218.0,367.0,412.0,0.0,501.0,NaN
4,Africa Eastern and Southern,AFE,Net migration,SM.POP.NETM,-90849.0,-1348.0,-24259.0,-16266.0,37452.0,11041.0,...,-92842.0,-199608.0,394925.0,-864708.0,-343075.0,-366105.0,-187410.0,-48955.0,-179444.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,Net migration,SM.POP.NETM,-6603.0,-6713.0,-7466.0,-7874.0,-8266.0,-8573.0,...,-40468.0,-56637.0,-14819.0,-31383.0,-33495.0,-34137.0,-33469.0,-15050.0,-15050.0,NaN
265,"Yemen, Rep.",YEM,Net migration,SM.POP.NETM,-17145.0,-17494.0,-17846.0,-18217.0,-18583.0,-18968.0,...,-23747.0,-30048.0,-38355.0,-39688.0,-39672.0,-39699.0,-39769.0,-86100.0,-101468.0,NaN
266,South Africa,ZAF,Net migration,SM.POP.NETM,18909.0,56098.0,68068.0,70976.0,74419.0,80687.0,...,63794.0,290874.0,644996.0,-866101.0,-10681.0,27265.0,22728.0,30852.0,10934.0,NaN
267,Zambia,ZMB,Net migration,SM.POP.NETM,-3894.0,-4357.0,-4756.0,-5029.0,-5214.0,-5370.0,...,15574.0,16580.0,16283.0,17285.0,20268.0,18019.0,18019.0,9015.0,9015.0,NaN
268,Zimbabwe,ZWE,Net migration,SM.POP.NETM,-8256.0,-8582.0,-8931.0,-9369.0,-10064.0,-10889.0,...,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-29955.0,-25005.0,NaN

In [3]:
index_list = list(range(0,2))
df.drop(df.index[index_list], inplace =True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
3,Aruba,ABW,Net migration,SM.POP.NETM,0.0,-569.0,-609.0,-646.0,-684.0,-726.0,...,134.0,88.0,177.0,170.0,218.0,367.0,412.0,0.0,501.0,NaN
4,Africa Eastern and Southern,AFE,Net migration,SM.POP.NETM,-90849.0,-1348.0,-24259.0,-16266.0,37452.0,11041.0,...,-92842.0,-199608.0,394925.0,-864708.0,-343075.0,-366105.0,-187410.0,-48955.0,-179444.0,NaN
5,Afghanistan,AFG,Net migration,SM.POP.NETM,2606.0,6109.0,7016.0,6681.0,7079.0,10695.0,...,48076.0,255611.0,-281739.0,-90238.0,-47090.0,-47205.0,-8082.0,166821.0,-183672.0,NaN
6,Africa Western and Central,AFW,Net migration,SM.POP.NETM,-847.0,-41547.0,-36399.0,-37435.0,-45534.0,-15985.0,...,-377305.0,-280418.0,-360393.0,-167286.0,-200823.0,-255888.0,-328552.0,-99761.0,-264802.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,Net migration,SM.POP.NETM,-6603.0,-6713.0,-7466.0,-7874.0,-8266.0,-8573.0,...,-40468.0,-56637.0,-14819.0,-31383.0,-33495.0,-34137.0,-33469.0,-15050.0,-15050.0,NaN
265,"Yemen, Rep.",YEM,Net migration,SM.POP.NETM,-17145.0,-17494.0,-17846.0,-18217.0,-18583.0,-18968.0,...,-23747.0,-30048.0,-38355.0,-39688.0,-39672.0,-39699.0,-39769.0,-86100.0,-101468.0,NaN
266,South Africa,ZAF,Net migration,SM.POP.NETM,18909.0,56098.0,68068.0,70976.0,74419.0,80687.0,...,63794.0,290874.0,644996.0,-866101.0,-10681.0,27265.0,22728.0,30852.0,10934.0,NaN
267,Zambia,ZMB,Net migration,SM.POP.NETM,-3894.0,-4357.0,-4756.0,-5029.0,-5214.0,-5370.0,...,15574.0,16580.0,16283.0,17285.0,20268.0,18019.0,18019.0,9015.0,9015.0,NaN
268,Zimbabwe,ZWE,Net migration,SM.POP.NETM,-8256.0,-8582.0,-8931.0,-9369.0,-10064.0,-10889.0,...,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-29955.0,-25005.0,NaN

In [4]:
index_list = list(range(1,14))
df.drop(df.index[index_list], inplace =True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
16,Australia,AUS,Net migration,SM.POP.NETM,86587.0,64374.0,58059.0,73375.0,91169.0,118655.0,...,214564.0,198120.0,209466.0,242184.0,244875.0,220307.0,235860.0,117929.0,117929.0,NaN
17,Austria,AUT,Net migration,SM.POP.NETM,-2274.0,-2418.0,1277.0,4768.0,3117.0,10295.0,...,56494.0,74263.0,115125.0,66282.0,45573.0,35404.0,41105.0,20314.0,20314.0,NaN
18,Azerbaijan,AZE,Net migration,SM.POP.NETM,-163.0,-182.0,-193.0,-200.0,-1636.0,-3842.0,...,2289.0,1084.0,1084.0,1484.0,1184.0,1583.0,392.0,1084.0,1084.0,NaN
19,Burundi,BDI,Net migration,SM.POP.NETM,-14647.0,15090.0,-15378.0,-11519.0,29635.0,-13952.0,...,-2295.0,-6856.0,-236447.0,-109490.0,-68450.0,68145.0,14241.0,-10186.0,-14415.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,Net migration,SM.POP.NETM,-6603.0,-6713.0,-7466.0,-7874.0,-8266.0,-8573.0,...,-40468.0,-56637.0,-14819.0,-31383.0,-33495.0,-34137.0,-33469.0,-15050.0,-15050.0,NaN
265,"Yemen, Rep.",YEM,Net migration,SM.POP.NETM,-17145.0,-17494.0,-17846.0,-18217.0,-18583.0,-18968.0,...,-23747.0,-30048.0,-38355.0,-39688.0,-39672.0,-39699.0,-39769.0,-86100.0,-101468.0,NaN
266,South Africa,ZAF,Net migration,SM.POP.NETM,18909.0,56098.0,68068.0,70976.0,74419.0,80687.0,...,63794.0,290874.0,644996.0,-866101.0,-10681.0,27265.0,22728.0,30852.0,10934.0,NaN
267,Zambia,ZMB,Net migration,SM.POP.NETM,-3894.0,-4357.0,-4756.0,-5029.0,-5214.0,-5370.0,...,15574.0,16580.0,16283.0,17285.0,20268.0,18019.0,18019.0,9015.0,9015.0,NaN
268,Zimbabwe,ZWE,Net migration,SM.POP.NETM,-8256.0,-8582.0,-8931.0,-9369.0,-10064.0,-10889.0,...,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-29955.0,-25005.0,NaN

In [5]:
index_list = list(range(2,69))
df.drop(df.index[index_list],inplace=True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
16,Australia,AUS,Net migration,SM.POP.NETM,86587.0,64374.0,58059.0,73375.0,91169.0,118655.0,...,214564.0,198120.0,209466.0,242184.0,244875.0,220307.0,235860.0,117929.0,117929.0,NaN
84,United Kingdom,GBR,Net migration,SM.POP.NETM,2344.0,-1995.0,-10512.0,-17416.0,-21275.0,-24045.0,...,268067.0,261389.0,254218.0,246940.0,239014.0,230577.0,221179.0,211063.0,202027.0,NaN
85,Georgia,GEO,Net migration,SM.POP.NETM,16740.0,18014.0,18976.0,19406.0,19373.0,18975.0,...,-27185.0,-16045.0,-13317.0,-10591.0,-7886.0,-5174.0,-5414.0,-2734.0,-2734.0,NaN
86,Ghana,GHA,Net migration,SM.POP.NETM,12176.0,-48780.0,-48017.0,-46510.0,-43475.0,-38520.0,...,-2388.0,-6316.0,-13308.0,7014.0,-4914.0,-19374.0,-21860.0,-297.0,-11253.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,Net migration,SM.POP.NETM,-6603.0,-6713.0,-7466.0,-7874.0,-8266.0,-8573.0,...,-40468.0,-56637.0,-14819.0,-31383.0,-33495.0,-34137.0,-33469.0,-15050.0,-15050.0,NaN
265,"Yemen, Rep.",YEM,Net migration,SM.POP.NETM,-17145.0,-17494.0,-17846.0,-18217.0,-18583.0,-18968.0,...,-23747.0,-30048.0,-38355.0,-39688.0,-39672.0,-39699.0,-39769.0,-86100.0,-101468.0,NaN
266,South Africa,ZAF,Net migration,SM.POP.NETM,18909.0,56098.0,68068.0,70976.0,74419.0,80687.0,...,63794.0,290874.0,644996.0,-866101.0,-10681.0,27265.0,22728.0,30852.0,10934.0,NaN
267,Zambia,ZMB,Net migration,SM.POP.NETM,-3894.0,-4357.0,-4756.0,-5029.0,-5214.0,-5370.0,...,15574.0,16580.0,16283.0,17285.0,20268.0,18019.0,18019.0,9015.0,9015.0,NaN
268,Zimbabwe,ZWE,Net migration,SM.POP.NETM,-8256.0,-8582.0,-8931.0,-9369.0,-10064.0,-10889.0,...,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-29955.0,-25005.0,NaN

In [6]:
index_list = list(range(3,99))
df.drop(df.index[index_list], inplace =True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
16,Australia,AUS,Net migration,SM.POP.NETM,86587.0,64374.0,58059.0,73375.0,91169.0,118655.0,...,214564.0,198120.0,209466.0,242184.0,244875.0,220307.0,235860.0,117929.0,117929.0,NaN
84,United Kingdom,GBR,Net migration,SM.POP.NETM,2344.0,-1995.0,-10512.0,-17416.0,-21275.0,-24045.0,...,268067.0,261389.0,254218.0,246940.0,239014.0,230577.0,221179.0,211063.0,202027.0,NaN
181,Nepal,NPL,Net migration,SM.POP.NETM,-13235.0,-10608.0,-9259.0,-8313.0,-6094.0,-1559.0,...,-373065.0,-310157.0,-221059.0,-98016.0,-78062.0,-81130.0,-70597.0,306664.0,296541.0,NaN
182,Nauru,NRU,Net migration,SM.POP.NETM,89.0,126.0,157.0,185.0,205.0,221.0,...,-34.0,-31.0,-31.0,-31.0,-34.0,-39.0,-107.0,-68.0,-66.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,Net migration,SM.POP.NETM,-6603.0,-6713.0,-7466.0,-7874.0,-8266.0,-8573.0,...,-40468.0,-56637.0,-14819.0,-31383.0,-33495.0,-34137.0,-33469.0,-15050.0,-15050.0,NaN
265,"Yemen, Rep.",YEM,Net migration,SM.POP.NETM,-17145.0,-17494.0,-17846.0,-18217.0,-18583.0,-18968.0,...,-23747.0,-30048.0,-38355.0,-39688.0,-39672.0,-39699.0,-39769.0,-86100.0,-101468.0,NaN
266,South Africa,ZAF,Net migration,SM.POP.NETM,18909.0,56098.0,68068.0,70976.0,74419.0,80687.0,...,63794.0,290874.0,644996.0,-866101.0,-10681.0,27265.0,22728.0,30852.0,10934.0,NaN
267,Zambia,ZMB,Net migration,SM.POP.NETM,-3894.0,-4357.0,-4756.0,-5029.0,-5214.0,-5370.0,...,15574.0,16580.0,16283.0,17285.0,20268.0,18019.0,18019.0,9015.0,9015.0,NaN
268,Zimbabwe,ZWE,Net migration,SM.POP.NETM,-8256.0,-8582.0,-8931.0,-9369.0,-10064.0,-10889.0,...,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-29955.0,-25005.0,NaN

In [7]:
index_list = list(range(4,12))
df.drop(df.index[index_list], inplace =True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
16,Australia,AUS,Net migration,SM.POP.NETM,86587.0,64374.0,58059.0,73375.0,91169.0,118655.0,...,214564.0,198120.0,209466.0,242184.0,244875.0,220307.0,235860.0,117929.0,117929.0,NaN
84,United Kingdom,GBR,Net migration,SM.POP.NETM,2344.0,-1995.0,-10512.0,-17416.0,-21275.0,-24045.0,...,268067.0,261389.0,254218.0,246940.0,239014.0,230577.0,221179.0,211063.0,202027.0,NaN
181,Nepal,NPL,Net migration,SM.POP.NETM,-13235.0,-10608.0,-9259.0,-8313.0,-6094.0,-1559.0,...,-373065.0,-310157.0,-221059.0,-98016.0,-78062.0,-81130.0,-70597.0,306664.0,296541.0,NaN
190,Philippines,PHL,Net migration,SM.POP.NETM,-155327.0,-221620.0,-232922.0,-239948.0,-241630.0,-242177.0,...,-199869.0,-237890.0,6954.0,79051.0,36111.0,-15371.0,-24066.0,-41937.0,-80125.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Kosovo,XKX,Net migration,SM.POP.NETM,-6603.0,-6713.0,-7466.0,-7874.0,-8266.0,-8573.0,...,-40468.0,-56637.0,-14819.0,-31383.0,-33495.0,-34137.0,-33469.0,-15050.0,-15050.0,NaN
265,"Yemen, Rep.",YEM,Net migration,SM.POP.NETM,-17145.0,-17494.0,-17846.0,-18217.0,-18583.0,-18968.0,...,-23747.0,-30048.0,-38355.0,-39688.0,-39672.0,-39699.0,-39769.0,-86100.0,-101468.0,NaN
266,South Africa,ZAF,Net migration,SM.POP.NETM,18909.0,56098.0,68068.0,70976.0,74419.0,80687.0,...,63794.0,290874.0,644996.0,-866101.0,-10681.0,27265.0,22728.0,30852.0,10934.0,NaN
267,Zambia,ZMB,Net migration,SM.POP.NETM,-3894.0,-4357.0,-4756.0,-5029.0,-5214.0,-5370.0,...,15574.0,16580.0,16283.0,17285.0,20268.0,18019.0,18019.0,9015.0,9015.0,NaN
268,Zimbabwe,ZWE,Net migration,SM.POP.NETM,-8256.0,-8582.0,-8931.0,-9369.0,-10064.0,-10889.0,...,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-59918.0,-29955.0,-25005.0,NaN

In [8]:
index_list = list(range(5,83))
df.drop(df.index[index_list], inplace =True)
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
16,Australia,AUS,Net migration,SM.POP.NETM,86587.0,64374.0,58059.0,73375.0,91169.0,118655.0,...,214564.0,198120.0,209466.0,242184.0,244875.0,220307.0,235860.0,117929.0,117929.0,NaN
84,United Kingdom,GBR,Net migration,SM.POP.NETM,2344.0,-1995.0,-10512.0,-17416.0,-21275.0,-24045.0,...,268067.0,261389.0,254218.0,246940.0,239014.0,230577.0,221179.0,211063.0,202027.0,NaN
181,Nepal,NPL,Net migration,SM.POP.NETM,-13235.0,-10608.0,-9259.0,-8313.0,-6094.0,-1559.0,...,-373065.0,-310157.0,-221059.0,-98016.0,-78062.0,-81130.0,-70597.0,306664.0,296541.0,NaN
190,Philippines,PHL,Net migration,SM.POP.NETM,-155327.0,-221620.0,-232922.0,-239948.0,-241630.0,-242177.0,...,-199869.0,-237890.0,6954.0,79051.0,36111.0,-15371.0,-24066.0,-41937.0,-80125.0,NaN

In [9]:
header_row = 0
df.columns = df.iloc[header_row]
df

2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
16,Australia,AUS,Net migration,SM.POP.NETM,86587.0,64374.0,58059.0,73375.0,91169.0,118655.0,...,214564.0,198120.0,209466.0,242184.0,244875.0,220307.0,235860.0,117929.0,117929.0,NaN
84,United Kingdom,GBR,Net migration,SM.POP.NETM,2344.0,-1995.0,-10512.0,-17416.0,-21275.0,-24045.0,...,268067.0,261389.0,254218.0,246940.0,239014.0,230577.0,221179.0,211063.0,202027.0,NaN
181,Nepal,NPL,Net migration,SM.POP.NETM,-13235.0,-10608.0,-9259.0,-8313.0,-6094.0,-1559.0,...,-373065.0,-310157.0,-221059.0,-98016.0,-78062.0,-81130.0,-70597.0,306664.0,296541.0,NaN
190,Philippines,PHL,Net migration,SM.POP.NETM,-155327.0,-221620.0,-232922.0,-239948.0,-241630.0,-242177.0,...,-199869.0,-237890.0,6954.0,79051.0,36111.0,-15371.0,-24066.0,-41937.0,-80125.0,NaN

In [10]:
df.drop([2],inplace=True)
df

2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
16,Australia,AUS,Net migration,SM.POP.NETM,86587.0,64374.0,58059.0,73375.0,91169.0,118655.0,...,214564.0,198120.0,209466.0,242184.0,244875.0,220307.0,235860.0,117929.0,117929.0,NaN
84,United Kingdom,GBR,Net migration,SM.POP.NETM,2344.0,-1995.0,-10512.0,-17416.0,-21275.0,-24045.0,...,268067.0,261389.0,254218.0,246940.0,239014.0,230577.0,221179.0,211063.0,202027.0,NaN
181,Nepal,NPL,Net migration,SM.POP.NETM,-13235.0,-10608.0,-9259.0,-8313.0,-6094.0,-1559.0,...,-373065.0,-310157.0,-221059.0,-98016.0,-78062.0,-81130.0,-70597.0,306664.0,296541.0,NaN
190,Philippines,PHL,Net migration,SM.POP.NETM,-155327.0,-221620.0,-232922.0,-239948.0,-241630.0,-242177.0,...,-199869.0,-237890.0,6954.0,79051.0,36111.0,-15371.0,-24066.0,-41937.0,-80125.0,NaN

In [11]:
df=df.reset_index()
df

2,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
0,16,Australia,AUS,Net migration,SM.POP.NETM,86587.0,64374.0,58059.0,73375.0,91169.0,...,214564.0,198120.0,209466.0,242184.0,244875.0,220307.0,235860.0,117929.0,117929.0,NaN
1,84,United Kingdom,GBR,Net migration,SM.POP.NETM,2344.0,-1995.0,-10512.0,-17416.0,-21275.0,...,268067.0,261389.0,254218.0,246940.0,239014.0,230577.0,221179.0,211063.0,202027.0,NaN
2,181,Nepal,NPL,Net migration,SM.POP.NETM,-13235.0,-10608.0,-9259.0,-8313.0,-6094.0,...,-373065.0,-310157.0,-221059.0,-98016.0,-78062.0,-81130.0,-70597.0,306664.0,296541.0,NaN
3,190,Philippines,PHL,Net migration,SM.POP.NETM,-155327.0,-221620.0,-232922.0,-239948.0,-241630.0,...,-199869.0,-237890.0,6954.0,79051.0,36111.0,-15371.0,-24066.0,-41937.0,-80125.0,NaN

In [12]:
df.fillna(0,inplace=True)
df

2,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
0,16,Australia,AUS,Net migration,SM.POP.NETM,86587.0,64374.0,58059.0,73375.0,91169.0,...,214564.0,198120.0,209466.0,242184.0,244875.0,220307.0,235860.0,117929.0,117929.0,0.0
1,84,United Kingdom,GBR,Net migration,SM.POP.NETM,2344.0,-1995.0,-10512.0,-17416.0,-21275.0,...,268067.0,261389.0,254218.0,246940.0,239014.0,230577.0,221179.0,211063.0,202027.0,0.0
2,181,Nepal,NPL,Net migration,SM.POP.NETM,-13235.0,-10608.0,-9259.0,-8313.0,-6094.0,...,-373065.0,-310157.0,-221059.0,-98016.0,-78062.0,-81130.0,-70597.0,306664.0,296541.0,0.0
3,190,Philippines,PHL,Net migration,SM.POP.NETM,-155327.0,-221620.0,-232922.0,-239948.0,-241630.0,...,-199869.0,-237890.0,6954.0,79051.0,36111.0,-15371.0,-24066.0,-41937.0,-80125.0,0.0

In [13]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  
    display(df)

2,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,1966.0,1967.0,1968.0,1969.0,1970.0,1971.0,1972.0,1973.0,1974.0,1975.0,1976.0,1977.0,1978.0,1979.0,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,1987.0,1988.0,1989.0,1990.0,1991.0,1992.0,1993.0,1994.0,1995.0,1996.0,1997.0,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
0,16,Australia,AUS,Net migration,SM.POP.NETM,86587.0,64374.0,58059.0,73375.0,91169.0,118655.0,110228.0,81057.0,101914.0,109720.0,258627.0,226406.0,55760.0,63870.0,62406.0,31122.0,32600.0,45424.0,45998.0,51702.0,86522.0,118568.0,107599.0,64184.0,74485.0,87895.0,109074.0,131625.0,150553.0,140156.0,95996.0,68867.0,34149.0,23422.0,53636.0,79727.0,82770.0,67260.0,72084.0,85011.0,109375.0,113907.0,107886.0,103907.0,109226.0,132109.0,192139.0,251231.0,278516.0,235881.0,166833.0,197748.0,235719.0,214564.0,198120.0,209466.0,242184.0,244875.0,220307.0,235860.0,117929.0,117929.0,0.0
1,84,United Kingdom,GBR,Net migration,SM.POP.NETM,2344.0,-1995.0,-10512.0,-17416.0,-21275.0,-24045.0,-26429.0,-26277.0,-26361.0,-26316.0,-26696.0,-27068.0,-24157.0,-22267.0,-21077.0,-19790.0,-18150.0,-16875.0,-15087.0,-13965.0,-12117.0,-10985.0,-10558.0,-10463.0,-9430.0,-8661.0,-7507.0,-6563.0,-4833.0,-3187.0,-701.0,3255.0,10003.0,20837.0,33409.0,48732.0,66293.0,86309.0,108637.0,133216.0,161157.0,186701.0,210510.0,230387.0,247447.0,261300.0,272651.0,279808.0,283762.0,284800.0,281588.0,277521.0,272601.0,268067.0,261389.0,254218.0,246940.0,239014.0,230577.0,221179.0,211063.0,202027.0,0.0
2,181,Nepal,NPL,Net migration,SM.POP.NETM,-13235.0,-10608.0,-9259.0,-8313.0,-6094.0,-1559.0,-3307.0,355.0,-757.0,-539.0,1846.0,-7285.0,-2111.0,-1089.0,-4360.0,-6677.0,-15131.0,2113.0,351.0,105.0,5084.0,-4859.0,-3898.0,1314.0,-19303.0,-30173.0,-47064.0,-72511.0,-64324.0,-39853.0,-650.0,17056.0,84106.0,-37782.0,-27423.0,-86300.0,-92417.0,-98574.0,-108537.0,-122704.0,-147403.0,-149185.0,-160257.0,-183002.0,-212507.0,-238799.0,-271254.0,-282748.0,-294886.0,-300762.0,-293613.0,-347554.0,-371708.0,-373065.0,-310157.0,-221059.0,-98016.0,-78062.0,-81130.0,-70597.0,306664.0,296541.0,0.0
3,190,Philippines,PHL,Net migration,SM.POP.NETM,-155327.0,-221620.0,-232922.0,-239948.0,-241630.0,-242177.0,-250618.0,-236043.0,-235037.0,-250039.0,-208125.0,-226375.0,-221928.0,-220160.0,-249665.0,-191812.0,-138957.0,-89147.0,-100900.0,-124344.0,-134411.0,-151928.0,-173001.0,-175518.0,-188441.0,-185754.0,-199600.0,-219289.0,-215159.0,-209926.0,-149089.0,-198673.0,-179039.0,-169227.0,-147940.0,-143386.0,5539.0,-3109.0,-24139.0,-59467.0,-122971.0,-185071.0,-195877.0,-204925.0,-182951.0,-223074.0,-235227.0,-217909.0,-190626.0,-232359.0,-183268.0,-103875.0,-156051.0,-199869.0,-237890.0,6954.0,79051.0,36111.0,-15371.0,-24066.0,-41937.0,-80125.0,0.0